# Generated by Django 3.1.4 on 2020-12-09 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\n            This can be a person or an organisation\n        ', max_length=255, unique=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='')),
                ('intro', models.TextField()),
                ('source_link', models.URLField(blank=True)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('building', 'Building'), ('infrastructure', 'Infrastructure'), ('motorsport', 'Motorsport')], max_length=255)),
                ('contract_completion', models.DateField(help_text="\n            yyyy-mm-dd (if the day is unknown, just put '01')\n        ")),
                ('contract_currency', models.CharField(blank=True, choices=[('BHD', 'Bahraini Dinar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('INR', 'Indian Rupee'), ('USD', 'US Dollar')], max_length=255)),
                ('contract_period', models.IntegerField(help_text='months')),
                ('contract_price', models.IntegerField(blank=True, null=True)),
                ('home_page', models.BooleanField(help_text='Should this be shown on the home page?')),
                ('projects_page', models.BooleanField(help_text='Should this be shown on the projects page?')),
                ('image', models.ImageField(upload_to='')),
                ('location', models.TextField(help_text="\n            1) Find it in Google Maps\n            2) Click on the 'share' button\n            3) Select 'Embed a map'\n            4) Select 'COPY HTML'\n\n        ")),
                ('slug', models.SlugField()),
                ('text', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects_as_client', to='core.affiliate')),
                ('consulting_engingeer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects_as_consulting_engingeer', to='core.affiliate')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_project_manager', to='core.affiliate')),
            ],
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('last_name', models.CharField(max_length=255)),
                ('position', models.CharField(help_text="\n            Their position in Cebarco (e.g. 'CEO')\n        ", max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
