# Generated by Django 3.1.4 on 2020-12-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201209_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='rank',
            field=models.IntegerField(default=1, help_text="\n            Their relative position on the 'About' page (i.e. 1, 2, 3, ...)\n        "),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='executive',
            name='position',
            field=models.CharField(help_text="\n            Their position in Cebarco (e.g. 'Director')\n        ", max_length=255),
        ),
    ]
