# Generated by Django 3.1.4 on 2020-12-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201210_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='rank',
            field=models.IntegerField(help_text="\n            Their relative position on the 'About' page (i.e. 1, 2, 3, ...)\n        ", unique=True),
        ),
    ]
