# Generated by Django 3.1.4 on 2020-12-10 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201210_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='consulting_engingeer',
            new_name='consulting_engineer',
        ),
    ]
