# Generated by Django 3.1.4 on 2020-12-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201210_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='undisclosed',
            field=models.BooleanField(default=False, help_text='Should the contract price be hidden from the public?'),
            preserve_default=False,
        ),
    ]
