# Generated by Django 3.1.4 on 2020-12-15 11:13

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_project_undisclosed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
