# Generated by Django 3.1.4 on 2020-12-15 12:55

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201215_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=markdownx.models.MarkdownxField(help_text='\n                You can use\n                <a href="https://www.markdownguide.org/cheat-sheet/">\n                markdown</a> here to format the text \n            '),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.TextField(blank=True, help_text="\n            1) Find it in Google Maps\n            2) Click on the 'share' button\n            3) Select 'Embed a map'\n            4) Select 'COPY HTML'\n\n        "),
        ),
        migrations.AlterField(
            model_name='project',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True, help_text='\n                You can use\n                <a href="https://www.markdownguide.org/cheat-sheet/">\n                markdown</a> here to format the text \n            '),
        ),
    ]
