# Generated by Django 3.1.4 on 2020-12-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201215_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='news_page',
            field=models.BooleanField(default=True, help_text='Should this be shown on the news page?'),
        ),
    ]
