# Generated by Django 3.1.4 on 2020-12-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_article_news_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projects_page',
            field=models.BooleanField(default=True, help_text='Should this be shown on the projects page?'),
        ),
    ]
