# Generated by Django 3.1.4 on 2020-12-16 12:39

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201216_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='crop',
            field=image_cropping.fields.ImageRatioField('image', '500x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='crop'),
        ),
    ]
