# Generated by Django 3.1.4 on 2020-12-21 13:48

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201216_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='image_ratio',
            field=image_cropping.fields.ImageRatioField('image', '1000x1000', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image ratio'),
        ),
    ]
