# Generated by Django 3.1.4 on 2020-12-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_executive_cropped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='home_page',
        ),
    ]
