# Generated by Django 3.1.4 on 2020-12-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_project_home_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='home_page',
            field=models.BooleanField(default=True, help_text='Should this be shown on the home page?'),
            preserve_default=False,
        ),
    ]
