# Generated by Django 3.1.4 on 2021-03-07 10:55

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cropped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='image_ratio',
            field=image_cropping.fields.ImageRatioField('image', '1000x1000', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image ratio'),
        ),
    ]
