# Generated by Django 3.1.4 on 2021-03-07 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210307_1416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
