# Generated by Django 3.1.3 on 2020-11-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('last_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('building', 'Building'), ('infrastructure', 'Infrastructure')], max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('consulting_engingeer', models.CharField(max_length=255)),
                ('contract_completion', models.DateField()),
                ('contract_period', models.IntegerField()),
                ('cost_engineer', models.CharField(max_length=255)),
                ('employer', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('location', models.CharField(max_length=255)),
                ('main_contractor', models.CharField(max_length=255)),
                ('project_cost', models.IntegerField()),
                ('project_cost_currency', models.CharField(choices=[('BHD', 'Bahraini Dinar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('INR', 'Indian Rupee'), ('USD', 'US Dollar')], max_length=255)),
                ('project_manager', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
