# Generated by Django 3.1.3 on 2020-11-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cost_engineer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='employer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
