# Generated by Django 3.1.3 on 2020-11-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201123_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='homepage',
            field=models.BooleanField(default=False),
        ),
    ]
