# Generated by Django 3.1.3 on 2020-11-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_cost_currency',
        ),
        migrations.AddField(
            model_name='project',
            name='project_currency',
            field=models.CharField(blank=True, choices=[('BHD', 'Bahraini Dinar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('INR', 'Indian Rupee'), ('USD', 'US Dollar')], max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='project_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_cost',
            field=models.IntegerField(null=True),
        ),
    ]
