# Generated by Django 3.1.3 on 2020-11-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201124_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_cost',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_value',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
