# Generated by Django 3.1.3 on 2020-11-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.URLField(blank=True),
        ),
    ]
