# Generated by Django 3.1.3 on 2020-11-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_article_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.TextField(),
        ),
    ]
