# Generated by Django 3.1.3 on 2020-11-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201127_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='source',
            new_name='source_link',
        ),
        migrations.AddField(
            model_name='article',
            name='source_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
