# Generated by Django 3.1.3 on 2020-11-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201127_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
