# Generated by Django 3.1.3 on 2020-11-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201127_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='intro',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
