# Generated by Django 3.1.3 on 2020-12-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_article_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract_period',
            field=models.IntegerField(help_text='in months'),
        ),
    ]
