# Generated by Django 3.1.3 on 2020-12-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20201201_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract_period',
            field=models.IntegerField(help_text='months'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.TextField(help_text='Google Maps embed (iframe)'),
        ),
    ]
