# Generated by Django 3.1.3 on 2020-12-07 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20201207_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_as_client', to='core.entity'),
        ),
        migrations.AlterField(
            model_name='project',
            name='consulting_engingeer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_as_consulting_engingeer', to='core.entity'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cost_engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_as_cost_engineer', to='core.entity'),
        ),
        migrations.AlterField(
            model_name='project',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_as_employer', to='core.entity'),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_as_main_contractor', to='core.entity'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_as_project_manager', to='core.entity'),
        ),
    ]
