# Generated by Django 3.1.3 on 2020-12-07 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20201207_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=models.CharField(blank=True, help_text="\n            For people, this should be the position they hold in their\n            organisation (e.g. 'Chairman'). For organisations, this is not\n            needed.\n        ", max_length=255),
        ),
        migrations.AlterField(
            model_name='entity',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='entity',
            name='team',
            field=models.BooleanField(help_text="\n            Are they to be included in the 'Our Team' section\n            on the 'About' page?\n        "),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_completion',
            field=models.DateField(help_text="\n            yyyy-mm-dd (if the day is unknown, just put '01')\n        "),
        ),
        migrations.AlterField(
            model_name='project',
            name='cost_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_as_cost_engineer', to='core.entity'),
        ),
        migrations.AlterField(
            model_name='project',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_as_employer', to='core.entity'),
        ),
        migrations.AlterField(
            model_name='project',
            name='homepage',
            field=models.BooleanField(help_text='Should this be shown on the homepage?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_as_project_manager', to='core.entity'),
        ),
    ]
