# Generated by Django 3.1.3 on 2020-12-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20201207_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_currency',
            new_name='contract_currency',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_cost',
            new_name='contract_price',
        ),
        migrations.RemoveField(
            model_name='project',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='project',
            name='main_contractor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_value',
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('building', 'Building'), ('infrastructure', 'Infrastructure'), ('motorsport', 'Motorsport')], max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.TextField(help_text="\n            1) Find it in Google Maps\n            2) Click on the 'share' button\n            3) Select 'Embed a map'\n            4) Select 'COPY HTML'\n\n        "),
        ),
    ]
