# Generated by Django 3.1.3 on 2020-12-08 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20201207_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\n            This can be a person or an organisation\n        ', max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'entities',
            },
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('last_name', models.CharField(max_length=255)),
                ('position', models.CharField(help_text="\n            e.g. 'CEO'\n        ", max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='cost_engineer',
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_as_client', to='core.affiliate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='consulting_engingeer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_as_consulting_engingeer', to='core.affiliate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_as_project_manager', to='core.affiliate'),
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
    ]
