# Generated by Django 3.1.3 on 2020-12-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20201208_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliate',
            options={},
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='executive',
            name='position',
            field=models.CharField(help_text="\n            Their position in Cebarco (e.g. 'CEO')\n        ", max_length=255),
        ),
        migrations.AlterField(
            model_name='executive',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
