# Generated by Django 3.1.3 on 2020-12-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20201208_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='homepage',
        ),
        migrations.AddField(
            model_name='project',
            name='home_page',
            field=models.BooleanField(default=True, help_text='Should this be shown on the home page?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='projects_page',
            field=models.BooleanField(default=True, help_text='Should this be shown on the projects page?'),
            preserve_default=False,
        ),
    ]
