# Generated by Django 3.1.3 on 2020-12-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20201208_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='name',
            field=models.CharField(help_text='\n            This can be a person or an organisation\n        ', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='slug',
            field=models.SlugField(),
        ),
    ]
