# Generated by Django 3.1.3 on 2020-12-08 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20201208_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects_as_client', to='core.affiliate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='consulting_engingeer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects_as_consulting_engingeer', to='core.affiliate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_as_project_manager', to='core.affiliate'),
        ),
    ]
